build_root:
  image_stream_tag:
    name: release
    namespace: openshift
    tag: golang-1.17
resources:
  '*':
    limits:
      memory: 4Gi
    requests:
      cpu: 100m
      memory: 200Mi
tests:
- as: kernel-crawling
  steps:
    post:
    - as: delete-vm
      commands: .openshift-ci/crawler/post.sh
      credentials:
      - mount_path: /tmp/secret/stackrox-kernel-packer-crawl
        name: stackrox-kernel-packer-crawl-test
        namespace: test-credentials
      from: src
      resources:
        requests:
          cpu: 4000m
          memory: 4000Mi
    pre:
    - as: create-vm
      commands: .openshift-ci/crawler/pre.sh
      credentials:
      - mount_path: /tmp/secret/stackrox-kernel-packer-crawl
        name: stackrox-kernel-packer-crawl-test
        namespace: test-credentials
      from: src
      resources:
        requests:
          cpu: 4000m
          memory: 4000Mi
    test:
    - as: crawling
      commands: .openshift-ci/crawler/crawling.sh
      credentials:
      - mount_path: /tmp/secret/stackrox-kernel-packer-crawl
        name: stackrox-kernel-packer-crawl-test
        namespace: test-credentials
      from: src
      resources:
        requests:
          cpu: 4000m
          memory: 4000Mi
      timeout: 6h0m0s
    - as: repackaging
      commands: .openshift-ci/crawler/repackaging.sh
      credentials:
      - mount_path: /tmp/secret/stackrox-kernel-packer-crawl
        name: stackrox-kernel-packer-crawl-test
        namespace: test-credentials
      from: src
      resources:
        requests:
          cpu: 4000m
          memory: 4000Mi
      timeout: 6h0m0s
zz_generated_metadata:
  branch: ddolgov-feature-crawling-on-vm
  org: stackrox
  repo: kernel-packer
