base_images:
  base:
    name: ubi-minimal
    namespace: ocp
    tag: "8"
resources:
  '*':
    limits:
      memory: 4Gi
    requests:
      cpu: 100m
      memory: 200Mi
tests:
- as: kernel-crawling
  steps:
    post:
    - as: delete-vm
      commands: .openshift-ci/crawler/post.sh
      from: base
      resources:
        requests:
          cpu: 4000m
          memory: 4000Mi
    pre:
    - as: create-vm
      commands: .openshift-ci/crawler/pre.sh
      from: base
      resources:
        requests:
          cpu: 4000m
          memory: 4000Mi
    test:
    - as: crawling
      commands: .openshift-ci/crawler/crawling.sh
      from: base
      resources:
        requests:
          cpu: 4000m
          memory: 4000Mi
      timeout: 6h0m0s
    - as: repackaging
      commands: .openshift-ci/crawler/repackaging.sh
      from: base
      resources:
        requests:
          cpu: 4000m
          memory: 4000Mi
      timeout: 6h0m0s
zz_generated_metadata:
  branch: ddolgov-feature-crawling-on-vm
  org: stackrox
  repo: kernel-packer
