build_root:
  project_image:
    dockerfile_path: kernel-crawler/Dockerfile
resources:
  '*':
    limits:
      memory: 4Gi
    requests:
      cpu: 100m
      memory: 200Mi
tests:
- as: unittests
  commands: go test -mod=mod -v ./...
  container:
    from: src
- as: crawl-kernels
  commands: .openshift-ci/crawl/main.sh
  container:
    from: src
  cron: 0 0,2,4,6,8,10,12,14,16,18,20,22 * * *
zz_generated_metadata:
  branch: ddolgov-feature-crawling
  org: stackrox
  repo: kernel-packer
