build_root:
  image_stream_tag:
    name: release
    namespace: openshift
    tag: golang-1.17
resources:
  '*':
    limits:
      memory: 4Gi
    requests:
      cpu: 100m
      memory: 200Mi
tests:
- as: unittests
  commands: go test -mod=mod -v ./...
  container:
    from: src
- as: crawl-kernels
  cron: 0 0,2,4,6,8,10,12,14,16,18,20,22 * * *
  commands: echo "crawl"
  container:
    from: src
zz_generated_metadata:
  branch: master
  org: stackrox
  repo: kernel-packer
