build_root:
  project_image:
    context_dir: kernel-crawler
    dockerfile_path: Dockerfile.ubi
images:
- context_dir: packers
  dockerfile_path: Dockerfile
  inputs:
    src:
      paths:
        - destination_dir: .
          source_path: .
  to: kernel-crawler-packers
resources:
  '*':
    limits:
      memory: 4Gi
    requests:
      cpu: 100m
      memory: 200Mi
tests:
- as: unittests
  commands: go test -mod=mod -v ./...
  container:
    from: src
- as: crawl-kernels
  steps:
    test:
    - as: crawl
      commands: .openshift-ci/crawler/crawl.sh
      credentials:
      - mount_path: /tmp/secret/stackrox-kernel-packer-crawl
        name: stackrox-kernel-packer-crawl-test
        namespace: test-credentials
      from: src
      resources:
        requests:
          cpu: 4000m
          memory: 4000Mi
    - as: repackage
      commands: .openshift-ci/crawler/repackage.sh
      from: kernel-crawler-packers
      resources:
        requests:
          cpu: 4000m
          memory: 4000Mi
  timeout: 6h0m0s
zz_generated_metadata:
  branch: ddolgov-feature-crawling
  org: stackrox
  repo: kernel-packer
